version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd web && yarn start"
    ports:
      - "3000:3000"
    tty: true
